taski/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  get 'error', to: 'pages#error'

  get 'blog', to: redirect('http://jordanhudgens.com')

  resources :projects do
    resources :tasks, except:[:index], controller: 'projects/tasks'
  end

  root 'pages#home'

  get '*path', to: redirect('/error')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  # root 'articles#index'
end

taski/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

taski/app/models/counter.rb
class Counter
  def self.calculate_percent_complete(completed_tasks, total_tasks)
    completed_tasks.to_f / total_tasks.to_f * 100
  end
end

taski/app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  after_initialize :set_defaults

  validates_presence_of :title, :description

  scope :almost_completed, -> { where('percent_complete > 75.0') }
  scope :still_needs_some_work, -> { where('percent_complete < 75.0') }

  def set_defaults
    self.percent_complete ||= 0.0
  end
end

taski/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  # callback will verify if the task is saved, and will updte the
  # percent_complete of the project that it belongs to
  after_save :update_percent_complete if :mark_completd?

  scope :completed, -> { where(completed: true) }

  mount_uploader :task_file, TaskFileUploader

  def mark_completd?
    self.completed == true
  end

  def update_percent_complete
    project = Project.find(self.project_id)
    count_of_completed_tasks = project.tasks.completed.count
    count_of_total_tasks = project.tasks.count
    project.update!(percent_complete: Counter.calculate_percent_complete(count_of_completed_tasks, count_of_total_tasks))
  end
end

taski/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

taski/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

taski/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
    @title = "My Cool Page!"
  end

  def home
    @projects = Project.all
  end

  def error
    puts "AAAAAAAAAAAAAA"
  end
end

taski/app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :new, :edit, :create, :update, :destroy]

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = @project.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_url(@task.project_id), notice: "Task was created successfully!" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_url(@task.project_id), notice: "Task was updated successfully!" }
        format.json { render :show, status: :created, location: @task }

      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_url(@task.project_id), notice: "Task was deleted successfully!" }
      format.json { head :no_content }
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :project_id, :completed, :task_file)
    end
end

taski/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    # @projects = Project.all
    # @projects = Project.almost_completed
    @projects = Project.still_needs_some_work
  end

  # GET /projects/1 or /projects/1.json
  def show
    @tasks = @project.tasks
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "A new Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :percent_complete)
    end
end

taski/app/helpers/application_helper.rb
module ApplicationHelper
end

taski/app/helpers/pages_helper.rb
module PagesHelper
end

taski/app/helpers/projects_helper.rb
module ProjectsHelper
end

taski/app/helpers/tasks_helper.rb
module TasksHelper
end

taski/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taski</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='logo'>
      <%= image_tag 'logos/logo.png', width:'100px' %>
    </div>

    <%= render 'shared/nav' %>

    <%= render 'shared/alerts' %>

    <%= yield %>
  </body>
</html>

taski/app/views/pages/about.html.erb
<h1>About us</h1>
<hr>
<p><%= @title %></p>
<%= 4+4 %></p>

taski/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

taski/app/views/pages/error.html.erb
<h1> Sorry, the page does not exist</h1>

Go back to <%= link_to 'homepage', root_path %>

taski/app/views/pages/home.html.erb
<h1>Home page</h1>

<div class='homepage-projects' >
  <%= render 'shared/projects' %>
</div>

taski/app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

taski/app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Percent complete:</strong>
    <%= project.percent_complete %>
  </p>

</div>

taski/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

taski/app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

taski/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

taski/app/views/projects/show.html.erb
<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

<h2> Tasks for project</h2>

<% @tasks.each do |task| %>
  <p><%= link_to task.title, project_task_path(@project.id, task.id) %></p>
<% end %>

<%= link_to "Add a new task for this project", new_project_task_path(project_id: @project.id) %>

taski/app/views/projects/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <% if @task.errors.any? %>
    <%= pluralize(@task.errors.count, "error") %> prohibited this project from being saved:

    <% @task.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.label "Attachment" %>
  <%= f.file_field :task_file %>

  <%= f.submit %>

<% end %>

taski/app/views/projects/tasks/edit.html.erb
<%= render 'form' %>

taski/app/views/projects/tasks/new.html.erb
<%= render 'form' %>

taski/app/views/projects/tasks/show.html.erb
<h1>Tasks#show</h1>

<h3>
  <%= @task.title %>
</h3>

<p><%= @task.description %></p>

<h4> Task started: <%= @task.created_at %></h4>

<% if @task.created_at != @task.updated_at %>
  <h4> Updated: <%= @task.updated_at %></h4>
<% end %>

<% if @task.completed == true %>
<p><em>Task already completed</em></p>
<% else %>
<p><em>Pending Task</em></p>
<% end %>

<% unless @task.task_file.blank? %>
  <p><%= link_to "Attachment", @task.task_file.to_s %></p>
<% end %>


<%= link_to "Edit", edit_project_task_path(@task.project_id, @task.id) %>
<%= link_to "Back to Project", project_path(@task.project_id) %>

taski/app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

taski/app/views/shared/_nav.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Blog', blog_path %>
<%= link_to 'Projects', projects_path %>

<% if current_user %>
  <%= button_to "Sign Out btn", destroy_user_session_path, method: :delete %>
  <%= link_to "Edit Account", edit_user_registration_path %>
<% else %>
  <%= link_to "Register", new_user_registration_path %>
  <%= link_to "Sign In", new_user_session_path %>
<% end %>

taski/app/views/shared/_projects.html.erb
<% @projects.each do |project| %>
  <p>
    <strong><%#= project.inspect %></strong>
    <strong><%= project.title %></strong>
      -
    <em><%= project.description %></em>
    <%#= "| #{project.percent_complete}" if project.percent_complete != nil %>
    <%= "| #{project.percent_complete}%" if project.percent_complete %>
  </p>
<% end %>